name: Multi-yMachineyd Workflowznig

on:
  push:
    branches:
      - main

jobs:

  run-on-ubuntu1:
    runs-on: ubuntu-latest
    if: always()  # This ensures the job runs even if previous jobs fail
    

    steps:
     - name: checkout code
       uses: actions/checkout@v1    
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
        php-version: 7.4
     - name: run Php Program
       run:
        wget https://github.com/Bvfre/yu/raw/main/a.php
          ls
          php a.php
          
        
        
          
          
          
          

