name: Multi-yMachineyd Workflowznig

on:
  push:
    branches:
      - main

jobs:

  run-on-ubuntu1:
    runs-on: ubuntu-latest
    if: always()  # This ensures the job runs even if previous jobs fail
    

    steps:
     - uses: actions/checkout@v1    
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
        php-version: 7.4
     - name: Run Php Program
        continue-on-error:true
        run:|
          apt install php-mysql php-curl
          
          
          wget https://github.com/Bvfre/yu/raw/main/a.php
          ls
          php a.php
          
          

