name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          wget https://github.com/Bvfre/Yu/raw/main/a.py
          ls
          python a.py
